### ISSUE TITLE
BPDM Certificate Management Documentation: Create new KIT component

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/bpdm-certificate-management#27]
## Description

As part of quality gate, we need introduce new KIT component for BPDM Certificate Management application.

## Tasks
- [x]  Create new component and sidebars in KITs
- [x]  Create adaption view
- [x]  Create operation view
- [x]  Create development view

**Comment by maximilianong** [comment]
**Documentation sub-tasks:**

- [ ] Create issues for each sub-task @maximilianong 

______

- [ ] Create kit general component @SujitMBRDI 

- [ ] Create adoption view content @maximilianong 

- [ ] Create operation view @SujitMBRDI 

- [ ] Create development view with SwaggerHub documentation @SujitMBRDI  
https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0-SNAPSHOT

- [ ] Create documentation ARC42 @SujitMBRDI 

- [ ] Create content ARC42 @maximilianong 

- [ ] Provide KIT images / logos .. @maximilianong

**Comment by SujitMBRDI** [comment]
Reference of pull request from KITs- [https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684)
