### ISSUE TITLE
Documentation: Bpdm certificate management 

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/bpdm-certificate-management#44]
## Description

In bpdm certificate management application repo, we need to introduce and maintain versions for documents mentioned in below tasks.

## Tasks

- [x]  Create decision records
- [x]  Create postman collection
- [x]  Create Api documentation
- [x]  Create reference documents for KITs like adaption, operation view and development view
